name: CI

on:
  push:
    branches: [ 'master', 'develop', 'v*', '*.x' ]
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Tests (Node ${{ matrix.node-version }})
        run: |
          npm install
          npm run test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
